const templates: Template[] = [
  {
    id: 1,
    count: 2,
    columns: 2,
    rows: 1,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 1, rows: 1 },
    ],
  },
  {
    id: 2,
    count: 6,
    columns: 3,
    rows: 2,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 1, rows: 1 },
      { x: 2, y: 0, columns: 1, rows: 1 },
      { x: 0, y: 1, columns: 1, rows: 1 },
      { x: 1, y: 1, columns: 1, rows: 1 },
      { x: 2, y: 1, columns: 1, rows: 1 },
    ],
  },
  {
    id: 3,
    count: 3,
    columns: 2,
    rows: 2,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 1, rows: 2 },
      { x: 0, y: 1, columns: 1, rows: 1 },
    ],
  },
  {
    id: 4,
    count: 3,
    columns: 2,
    rows: 2,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 2 },
      { x: 1, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 1, columns: 1, rows: 1 },
    ],
  },
  {
    id: 5,
    count: 9,
    columns: 3,
    rows: 3,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 1, rows: 1 },
      { x: 2, y: 0, columns: 1, rows: 1 },
      { x: 0, y: 1, columns: 1, rows: 1 },
      { x: 1, y: 1, columns: 1, rows: 1 },
      { x: 2, y: 1, columns: 1, rows: 1 },
      { x: 0, y: 2, columns: 1, rows: 1 },
      { x: 1, y: 2, columns: 1, rows: 1 },
      { x: 2, y: 2, columns: 1, rows: 1 },
    ],
  },
  {
    id: 6,
    count: 4,
    columns: 2,
    rows: 2,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 1, rows: 1 },
      { x: 0, y: 1, columns: 1, rows: 1 },
      { x: 1, y: 1, columns: 1, rows: 1 },
    ],
  },
  {
    id: 7,
    count: 13,
    columns: 4,
    rows: 4,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 1, rows: 1 },
      { x: 2, y: 0, columns: 1, rows: 1 },
      { x: 3, y: 0, columns: 1, rows: 1 },
      { x: 0, y: 1, columns: 1, rows: 1 },
      { x: 1, y: 1, columns: 2, rows: 2 },
      { x: 3, y: 1, columns: 1, rows: 1 },
      { x: 0, y: 2, columns: 1, rows: 1 },
      { x: 3, y: 2, columns: 1, rows: 1 },
      { x: 0, y: 3, columns: 1, rows: 1 },
      { x: 1, y: 3, columns: 1, rows: 1 },
      { x: 2, y: 3, columns: 1, rows: 1 },
      { x: 3, y: 3, columns: 1, rows: 1 },
    ],
  },
  {
    id: 8,
    count: 2,
    columns: 3,
    rows: 1,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 2, rows: 1 },
    ],
  },
  {
    id: 9,
    count: 32,
    columns: 8,
    rows: 4,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 1, rows: 1 },
      { x: 2, y: 0, columns: 1, rows: 1 },
      { x: 3, y: 0, columns: 1, rows: 1 },
      { x: 4, y: 0, columns: 1, rows: 1 },
      { x: 5, y: 0, columns: 1, rows: 1 },
      { x: 6, y: 0, columns: 1, rows: 1 },
      { x: 7, y: 0, columns: 1, rows: 1 },
      { x: 0, y: 1, columns: 1, rows: 1 },
      { x: 1, y: 1, columns: 1, rows: 1 },
      { x: 2, y: 1, columns: 1, rows: 1 },
      { x: 3, y: 1, columns: 1, rows: 1 },
      { x: 4, y: 1, columns: 1, rows: 1 },
      { x: 5, y: 1, columns: 1, rows: 1 },
      { x: 6, y: 1, columns: 1, rows: 1 },
      { x: 7, y: 1, columns: 1, rows: 1 },
      { x: 0, y: 2, columns: 1, rows: 1 },
      { x: 1, y: 2, columns: 1, rows: 1 },
      { x: 2, y: 2, columns: 1, rows: 1 },
      { x: 3, y: 2, columns: 1, rows: 1 },
      { x: 4, y: 2, columns: 1, rows: 1 },
      { x: 5, y: 2, columns: 1, rows: 1 },
      { x: 6, y: 2, columns: 1, rows: 1 },
      { x: 7, y: 2, columns: 1, rows: 1 },
      { x: 0, y: 3, columns: 1, rows: 1 },
      { x: 1, y: 3, columns: 1, rows: 1 },
      { x: 2, y: 3, columns: 1, rows: 1 },
      { x: 3, y: 3, columns: 1, rows: 1 },
      { x: 4, y: 3, columns: 1, rows: 1 },
      { x: 5, y: 3, columns: 1, rows: 1 },
      { x: 6, y: 3, columns: 1, rows: 1 },
      { x: 7, y: 3, columns: 1, rows: 1 },
    ],
  },
  {
    id: 10,
    count: 2,
    columns: 1,
    rows: 2,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 0, y: 1, columns: 1, rows: 1 },
    ],
  },
  {
    id: 11,
    count: 2,
    columns: 3,
    rows: 1,
    regions: [
      { x: 0, y: 0, columns: 2, rows: 1 },
      { x: 2, y: 0, columns: 1, rows: 1 },
    ],
  },
  {
    id: 12,
    count: 3,
    columns: 3,
    rows: 1,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 1, rows: 1 },
      { x: 2, y: 0, columns: 1, rows: 1 },
    ],
  },
  {
    id: 13,
    count: 3,
    columns: 2,
    rows: 2,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 1, rows: 1 },
      { x: 0, y: 1, columns: 2, rows: 1 },
    ],
  },
  {
    id: 14,
    count: 3,
    columns: 2,
    rows: 2,
    regions: [
      { x: 0, y: 0, columns: 2, rows: 1 },
      { x: 0, y: 1, columns: 1, rows: 1 },
      { x: 1, y: 1, columns: 1, rows: 1 },
    ],
  },
  {
    id: 15,
    count: 5,
    columns: 6,
    rows: 2,
    regions: [
      { x: 0, y: 0, columns: 3, rows: 1 },
      { x: 3, y: 0, columns: 3, rows: 1 },
      { x: 0, y: 1, columns: 2, rows: 1 },
      { x: 2, y: 1, columns: 2, rows: 1 },
      { x: 4, y: 1, columns: 2, rows: 1 },
    ],
  },
  {
    id: 16,
    count: 4,
    columns: 2,
    rows: 3,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 1, rows: 3 },
      { x: 0, y: 1, columns: 1, rows: 1 },
      { x: 0, y: 2, columns: 1, rows: 1 },
    ],
  },
  {
    id: 17,
    count: 4,
    columns: 2,
    rows: 3,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 3 },
      { x: 1, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 1, columns: 1, rows: 1 },
      { x: 1, y: 2, columns: 1, rows: 1 },
    ],
  },
  {
    id: 18,
    count: 5,
    columns: 3,
    rows: 3,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 2 },
      { x: 1, y: 0, columns: 1, rows: 2 },
      { x: 2, y: 0, columns: 1, rows: 1 },
      { x: 2, y: 1, columns: 1, rows: 2 },
      { x: 0, y: 2, columns: 2, rows: 1 },
    ],
  },
  {
    id: 19,
    count: 4,
    columns: 3,
    rows: 3,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 2, rows: 3 },
      { x: 0, y: 1, columns: 1, rows: 1 },
      { x: 0, y: 2, columns: 1, rows: 1 },
    ],
  },
  {
    id: 20,
    count: 4,
    columns: 3,
    rows: 3,
    regions: [
      { x: 0, y: 0, columns: 2, rows: 3 },
      { x: 2, y: 0, columns: 1, rows: 1 },
      { x: 2, y: 1, columns: 1, rows: 1 },
      { x: 2, y: 2, columns: 1, rows: 1 },
    ],
  },
  {
    id: 21,
    count: 10,
    columns: 4,
    rows: 4,
    regions: [
      { x: 0, y: 0, columns: 2, rows: 2 },
      { x: 2, y: 0, columns: 1, rows: 1 },
      { x: 3, y: 0, columns: 1, rows: 1 },
      { x: 2, y: 1, columns: 1, rows: 1 },
      { x: 3, y: 1, columns: 1, rows: 1 },
      { x: 0, y: 2, columns: 1, rows: 1 },
      { x: 1, y: 2, columns: 1, rows: 1 },
      { x: 2, y: 2, columns: 2, rows: 2 },
      { x: 0, y: 3, columns: 1, rows: 1 },
      { x: 1, y: 3, columns: 1, rows: 1 },
    ],
  },
  {
    id: 22,
    count: 16,
    columns: 4,
    rows: 4,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 1, rows: 1 },
      { x: 2, y: 0, columns: 1, rows: 1 },
      { x: 3, y: 0, columns: 1, rows: 1 },
      { x: 0, y: 1, columns: 1, rows: 1 },
      { x: 1, y: 1, columns: 1, rows: 1 },
      { x: 2, y: 1, columns: 1, rows: 1 },
      { x: 3, y: 1, columns: 1, rows: 1 },
      { x: 0, y: 2, columns: 1, rows: 1 },
      { x: 1, y: 2, columns: 1, rows: 1 },
      { x: 2, y: 2, columns: 1, rows: 1 },
      { x: 3, y: 2, columns: 1, rows: 1 },
      { x: 0, y: 3, columns: 1, rows: 1 },
      { x: 1, y: 3, columns: 1, rows: 1 },
      { x: 2, y: 3, columns: 1, rows: 1 },
      { x: 3, y: 3, columns: 1, rows: 1 },
    ],
  },
  {
    id: 23,
    count: 7,
    columns: 3,
    rows: 4,
    regions: [
      { x: 0, y: 0, columns: 2, rows: 2 },
      { x: 2, y: 0, columns: 1, rows: 1 },
      { x: 2, y: 1, columns: 1, rows: 1 },
      { x: 0, y: 2, columns: 1, rows: 2 },
      { x: 1, y: 2, columns: 1, rows: 2 },
      { x: 2, y: 2, columns: 1, rows: 1 },
      { x: 2, y: 3, columns: 1, rows: 1 },
    ],
  },
  {
    id: 24,
    count: 9,
    columns: 15,
    rows: 7,
    regions: [
      { x: 0, y: 0, columns: 5, rows: 2 },
      { x: 5, y: 0, columns: 5, rows: 2 },
      { x: 10, y: 0, columns: 5, rows: 2 },
      { x: 0, y: 2, columns: 4, rows: 3 },
      { x: 4, y: 2, columns: 7, rows: 3 },
      { x: 11, y: 2, columns: 4, rows: 3 },
      { x: 0, y: 5, columns: 5, rows: 2 },
      { x: 5, y: 5, columns: 5, rows: 2 },
      { x: 10, y: 5, columns: 5, rows: 2 },
    ],
  },
  {
    id: 25,
    count: 5,
    columns: 6,
    rows: 2,
    regions: [
      { x: 0, y: 0, columns: 2, rows: 1 },
      { x: 2, y: 0, columns: 2, rows: 1 },
      { x: 4, y: 0, columns: 2, rows: 1 },
      { x: 0, y: 1, columns: 3, rows: 1 },
      { x: 3, y: 1, columns: 3, rows: 1 },
    ],
  },
  {
    id: 26,
    count: 21,
    columns: 7,
    rows: 3,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 1, rows: 1 },
      { x: 2, y: 0, columns: 1, rows: 1 },
      { x: 3, y: 0, columns: 1, rows: 1 },
      { x: 4, y: 0, columns: 1, rows: 1 },
      { x: 5, y: 0, columns: 1, rows: 1 },
      { x: 6, y: 0, columns: 1, rows: 1 },
      { x: 0, y: 1, columns: 1, rows: 1 },
      { x: 1, y: 1, columns: 1, rows: 1 },
      { x: 2, y: 1, columns: 1, rows: 1 },
      { x: 3, y: 1, columns: 1, rows: 1 },
      { x: 4, y: 1, columns: 1, rows: 1 },
      { x: 5, y: 1, columns: 1, rows: 1 },
      { x: 6, y: 1, columns: 1, rows: 1 },
      { x: 0, y: 2, columns: 1, rows: 1 },
      { x: 1, y: 2, columns: 1, rows: 1 },
      { x: 2, y: 2, columns: 1, rows: 1 },
      { x: 3, y: 2, columns: 1, rows: 1 },
      { x: 4, y: 2, columns: 1, rows: 1 },
      { x: 5, y: 2, columns: 1, rows: 1 },
      { x: 6, y: 2, columns: 1, rows: 1 },
    ],
  },
  {
    id: 27,
    count: 20,
    columns: 5,
    rows: 4,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 1, rows: 1 },
      { x: 2, y: 0, columns: 1, rows: 1 },
      { x: 3, y: 0, columns: 1, rows: 1 },
      { x: 4, y: 0, columns: 1, rows: 1 },
      { x: 0, y: 1, columns: 1, rows: 1 },
      { x: 1, y: 1, columns: 1, rows: 1 },
      { x: 2, y: 1, columns: 1, rows: 1 },
      { x: 3, y: 1, columns: 1, rows: 1 },
      { x: 4, y: 1, columns: 1, rows: 1 },
      { x: 0, y: 2, columns: 1, rows: 1 },
      { x: 1, y: 2, columns: 1, rows: 1 },
      { x: 2, y: 2, columns: 1, rows: 1 },
      { x: 3, y: 2, columns: 1, rows: 1 },
      { x: 4, y: 2, columns: 1, rows: 1 },
      { x: 0, y: 3, columns: 1, rows: 1 },
      { x: 1, y: 3, columns: 1, rows: 1 },
      { x: 2, y: 3, columns: 1, rows: 1 },
      { x: 3, y: 3, columns: 1, rows: 1 },
      { x: 4, y: 3, columns: 1, rows: 1 },
    ],
  },
  {
    id: 28,
    count: 6,
    columns: 2,
    rows: 3,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 1, rows: 1 },
      { x: 0, y: 1, columns: 1, rows: 1 },
      { x: 1, y: 1, columns: 1, rows: 1 },
      { x: 0, y: 2, columns: 1, rows: 1 },
      { x: 1, y: 2, columns: 1, rows: 1 },
    ],
  },
  {
    id: 29,
    count: 3,
    columns: 1,
    rows: 3,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 0, y: 1, columns: 1, rows: 1 },
      { x: 0, y: 2, columns: 1, rows: 1 },
    ],
  },
  {
    id: 30,
    count: 4,
    columns: 4,
    rows: 1,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 1, rows: 1 },
      { x: 2, y: 0, columns: 1, rows: 1 },
      { x: 3, y: 0, columns: 1, rows: 1 },
    ],
  },
  {
    id: 31,
    count: 4,
    columns: 3,
    rows: 4,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 2 },
      { x: 1, y: 0, columns: 1, rows: 2 },
      { x: 2, y: 0, columns: 1, rows: 2 },
      { x: 0, y: 2, columns: 3, rows: 2 },
    ],
  },
  {
    id: 32,
    count: 4,
    columns: 3,
    rows: 4,
    regions: [
      { x: 0, y: 0, columns: 3, rows: 2 },
      { x: 0, y: 2, columns: 1, rows: 2 },
      { x: 1, y: 2, columns: 1, rows: 2 },
      { x: 2, y: 2, columns: 1, rows: 2 },
    ],
  },
  {
    id: 33,
    count: 48,
    columns: 8,
    rows: 6,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 1, rows: 1 },
      { x: 2, y: 0, columns: 1, rows: 1 },
      { x: 3, y: 0, columns: 1, rows: 1 },
      { x: 4, y: 0, columns: 1, rows: 1 },
      { x: 5, y: 0, columns: 1, rows: 1 },
      { x: 6, y: 0, columns: 1, rows: 1 },
      { x: 7, y: 0, columns: 1, rows: 1 },
      { x: 0, y: 1, columns: 1, rows: 1 },
      { x: 1, y: 1, columns: 1, rows: 1 },
      { x: 2, y: 1, columns: 1, rows: 1 },
      { x: 3, y: 1, columns: 1, rows: 1 },
      { x: 4, y: 1, columns: 1, rows: 1 },
      { x: 5, y: 1, columns: 1, rows: 1 },
      { x: 6, y: 1, columns: 1, rows: 1 },
      { x: 7, y: 1, columns: 1, rows: 1 },
      { x: 0, y: 2, columns: 1, rows: 1 },
      { x: 1, y: 2, columns: 1, rows: 1 },
      { x: 2, y: 2, columns: 1, rows: 1 },
      { x: 3, y: 2, columns: 1, rows: 1 },
      { x: 4, y: 2, columns: 1, rows: 1 },
      { x: 5, y: 2, columns: 1, rows: 1 },
      { x: 6, y: 2, columns: 1, rows: 1 },
      { x: 7, y: 2, columns: 1, rows: 1 },
      { x: 0, y: 3, columns: 1, rows: 1 },
      { x: 1, y: 3, columns: 1, rows: 1 },
      { x: 2, y: 3, columns: 1, rows: 1 },
      { x: 3, y: 3, columns: 1, rows: 1 },
      { x: 4, y: 3, columns: 1, rows: 1 },
      { x: 5, y: 3, columns: 1, rows: 1 },
      { x: 6, y: 3, columns: 1, rows: 1 },
      { x: 7, y: 3, columns: 1, rows: 1 },
      { x: 0, y: 4, columns: 1, rows: 1 },
      { x: 1, y: 4, columns: 1, rows: 1 },
      { x: 2, y: 4, columns: 1, rows: 1 },
      { x: 3, y: 4, columns: 1, rows: 1 },
      { x: 4, y: 4, columns: 1, rows: 1 },
      { x: 5, y: 4, columns: 1, rows: 1 },
      { x: 6, y: 4, columns: 1, rows: 1 },
      { x: 7, y: 4, columns: 1, rows: 1 },
      { x: 0, y: 5, columns: 1, rows: 1 },
      { x: 1, y: 5, columns: 1, rows: 1 },
      { x: 2, y: 5, columns: 1, rows: 1 },
      { x: 3, y: 5, columns: 1, rows: 1 },
      { x: 4, y: 5, columns: 1, rows: 1 },
      { x: 5, y: 5, columns: 1, rows: 1 },
      { x: 6, y: 5, columns: 1, rows: 1 },
      { x: 7, y: 5, columns: 1, rows: 1 },
    ],
  },
  {
    id: 34,
    count: 3,
    columns: 2,
    rows: 3,
    regions: [
      { x: 0, y: 0, columns: 2, rows: 1 },
      { x: 0, y: 1, columns: 1, rows: 2 },
      { x: 1, y: 1, columns: 1, rows: 2 },
    ],
  },
  {
    id: 35,
    count: 12,
    columns: 4,
    rows: 3,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 1, rows: 1 },
      { x: 2, y: 0, columns: 1, rows: 1 },
      { x: 3, y: 0, columns: 1, rows: 1 },
      { x: 0, y: 1, columns: 1, rows: 1 },
      { x: 1, y: 1, columns: 1, rows: 1 },
      { x: 2, y: 1, columns: 1, rows: 1 },
      { x: 3, y: 1, columns: 1, rows: 1 },
      { x: 0, y: 2, columns: 1, rows: 1 },
      { x: 1, y: 2, columns: 1, rows: 1 },
      { x: 2, y: 2, columns: 1, rows: 1 },
      { x: 3, y: 2, columns: 1, rows: 1 },
    ],
  },
  {
    id: 36,
    count: 12,
    columns: 3,
    rows: 4,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 1, rows: 1 },
      { x: 2, y: 0, columns: 1, rows: 1 },
      { x: 0, y: 1, columns: 1, rows: 1 },
      { x: 1, y: 1, columns: 1, rows: 1 },
      { x: 2, y: 1, columns: 1, rows: 1 },
      { x: 0, y: 2, columns: 1, rows: 1 },
      { x: 1, y: 2, columns: 1, rows: 1 },
      { x: 2, y: 2, columns: 1, rows: 1 },
      { x: 0, y: 3, columns: 1, rows: 1 },
      { x: 1, y: 3, columns: 1, rows: 1 },
      { x: 2, y: 3, columns: 1, rows: 1 },
    ],
  },
  {
    id: 37,
    count: 8,
    columns: 4,
    rows: 2,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 1, rows: 1 },
      { x: 2, y: 0, columns: 1, rows: 1 },
      { x: 3, y: 0, columns: 1, rows: 1 },
      { x: 0, y: 1, columns: 1, rows: 1 },
      { x: 1, y: 1, columns: 1, rows: 1 },
      { x: 2, y: 1, columns: 1, rows: 1 },
      { x: 3, y: 1, columns: 1, rows: 1 },
    ],
  },
  {
    id: 38,
    count: 35,
    columns: 7,
    rows: 5,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 1, rows: 1 },
      { x: 2, y: 0, columns: 1, rows: 1 },
      { x: 3, y: 0, columns: 1, rows: 1 },
      { x: 4, y: 0, columns: 1, rows: 1 },
      { x: 5, y: 0, columns: 1, rows: 1 },
      { x: 6, y: 0, columns: 1, rows: 1 },
      { x: 0, y: 1, columns: 1, rows: 1 },
      { x: 1, y: 1, columns: 1, rows: 1 },
      { x: 2, y: 1, columns: 1, rows: 1 },
      { x: 3, y: 1, columns: 1, rows: 1 },
      { x: 4, y: 1, columns: 1, rows: 1 },
      { x: 5, y: 1, columns: 1, rows: 1 },
      { x: 6, y: 1, columns: 1, rows: 1 },
      { x: 0, y: 2, columns: 1, rows: 1 },
      { x: 1, y: 2, columns: 1, rows: 1 },
      { x: 2, y: 2, columns: 1, rows: 1 },
      { x: 3, y: 2, columns: 1, rows: 1 },
      { x: 4, y: 2, columns: 1, rows: 1 },
      { x: 5, y: 2, columns: 1, rows: 1 },
      { x: 6, y: 2, columns: 1, rows: 1 },
      { x: 0, y: 3, columns: 1, rows: 1 },
      { x: 1, y: 3, columns: 1, rows: 1 },
      { x: 2, y: 3, columns: 1, rows: 1 },
      { x: 3, y: 3, columns: 1, rows: 1 },
      { x: 4, y: 3, columns: 1, rows: 1 },
      { x: 5, y: 3, columns: 1, rows: 1 },
      { x: 6, y: 3, columns: 1, rows: 1 },
      { x: 0, y: 4, columns: 1, rows: 1 },
      { x: 1, y: 4, columns: 1, rows: 1 },
      { x: 2, y: 4, columns: 1, rows: 1 },
      { x: 3, y: 4, columns: 1, rows: 1 },
      { x: 4, y: 4, columns: 1, rows: 1 },
      { x: 5, y: 4, columns: 1, rows: 1 },
      { x: 6, y: 4, columns: 1, rows: 1 },
    ],
  },
  {
    id: 39,
    count: 7,
    columns: 3,
    rows: 4,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 1, rows: 2 },
      { x: 2, y: 0, columns: 1, rows: 2 },
      { x: 0, y: 1, columns: 1, rows: 1 },
      { x: 0, y: 2, columns: 1, rows: 1 },
      { x: 1, y: 2, columns: 2, rows: 2 },
      { x: 0, y: 3, columns: 1, rows: 1 },
    ],
  },
  {
    id: 40,
    count: 7,
    columns: 3,
    rows: 4,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 2 },
      { x: 1, y: 0, columns: 1, rows: 1 },
      { x: 2, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 1, columns: 1, rows: 1 },
      { x: 2, y: 1, columns: 1, rows: 1 },
      { x: 0, y: 2, columns: 1, rows: 2 },
      { x: 1, y: 2, columns: 2, rows: 2 },
    ],
  },
  {
    id: 41,
    count: 5,
    columns: 3,
    rows: 4,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 2, rows: 4 },
      { x: 0, y: 1, columns: 1, rows: 1 },
      { x: 0, y: 2, columns: 1, rows: 1 },
      { x: 0, y: 3, columns: 1, rows: 1 },
    ],
  },
  {
    id: 42,
    count: 6,
    columns: 6,
    rows: 1,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 1, rows: 1 },
      { x: 2, y: 0, columns: 1, rows: 1 },
      { x: 3, y: 0, columns: 1, rows: 1 },
      { x: 4, y: 0, columns: 1, rows: 1 },
      { x: 5, y: 0, columns: 1, rows: 1 },
    ],
  },
  {
    id: 43,
    count: 8,
    columns: 2,
    rows: 4,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 1, rows: 1 },
      { x: 0, y: 1, columns: 1, rows: 1 },
      { x: 1, y: 1, columns: 1, rows: 1 },
      { x: 0, y: 2, columns: 1, rows: 1 },
      { x: 1, y: 2, columns: 1, rows: 1 },
      { x: 0, y: 3, columns: 1, rows: 1 },
      { x: 1, y: 3, columns: 1, rows: 1 },
    ],
  },
  {
    id: 44,
    count: 5,
    columns: 5,
    rows: 1,
    regions: [
      { x: 0, y: 0, columns: 1, rows: 1 },
      { x: 1, y: 0, columns: 1, rows: 1 },
      { x: 2, y: 0, columns: 1, rows: 1 },
      { x: 3, y: 0, columns: 1, rows: 1 },
      { x: 4, y: 0, columns: 1, rows: 1 },
    ],
  },
];

export type Region = {
  x: number;
  y: number;
  columns: number;
  rows: number;
};

export type Template = {
  id: number;
  count: number;
  columns: number;
  rows: number;
  regions: Region[];
};

export const templatesByCount: { [key: number]: Template[] } = templates.reduce((r, a) => {
  r[a.count] = r[a.count] || [];
  r[a.count].push(a);
  return r;
}, Object.create(null));

// export function getTemplateById(id: number): Template | undefined {
//   return templates.find((x) => x.id === id);
// }
